name: Test 3GPP specs

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test
        run: |
          cd .test
          npm install
          cd ..
          npm i --global mocha
          mocha .test/dist/index.js
